// Generated by gencpp from file mission_node/Bounding_box.msg
// DO NOT EDIT!


#ifndef MISSION_NODE_MESSAGE_BOUNDING_BOX_H
#define MISSION_NODE_MESSAGE_BOUNDING_BOX_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mission_node
{
template <class ContainerAllocator>
struct Bounding_box_
{
  typedef Bounding_box_<ContainerAllocator> Type;

  Bounding_box_()
    : detected_class()
    , cx(0)
    , cy(0)  {
    }
  Bounding_box_(const ContainerAllocator& _alloc)
    : detected_class(_alloc)
    , cx(0)
    , cy(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _detected_class_type;
  _detected_class_type detected_class;

   typedef int16_t _cx_type;
  _cx_type cx;

   typedef int16_t _cy_type;
  _cy_type cy;





  typedef boost::shared_ptr< ::mission_node::Bounding_box_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mission_node::Bounding_box_<ContainerAllocator> const> ConstPtr;

}; // struct Bounding_box_

typedef ::mission_node::Bounding_box_<std::allocator<void> > Bounding_box;

typedef boost::shared_ptr< ::mission_node::Bounding_box > Bounding_boxPtr;
typedef boost::shared_ptr< ::mission_node::Bounding_box const> Bounding_boxConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mission_node::Bounding_box_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mission_node::Bounding_box_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mission_node::Bounding_box_<ContainerAllocator1> & lhs, const ::mission_node::Bounding_box_<ContainerAllocator2> & rhs)
{
  return lhs.detected_class == rhs.detected_class &&
    lhs.cx == rhs.cx &&
    lhs.cy == rhs.cy;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mission_node::Bounding_box_<ContainerAllocator1> & lhs, const ::mission_node::Bounding_box_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mission_node

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mission_node::Bounding_box_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mission_node::Bounding_box_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mission_node::Bounding_box_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mission_node::Bounding_box_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mission_node::Bounding_box_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mission_node::Bounding_box_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mission_node::Bounding_box_<ContainerAllocator> >
{
  static const char* value()
  {
    return "899615dfe4b53d2fa5fba3dfbb98944a";
  }

  static const char* value(const ::mission_node::Bounding_box_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x899615dfe4b53d2fULL;
  static const uint64_t static_value2 = 0xa5fba3dfbb98944aULL;
};

template<class ContainerAllocator>
struct DataType< ::mission_node::Bounding_box_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mission_node/Bounding_box";
  }

  static const char* value(const ::mission_node::Bounding_box_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mission_node::Bounding_box_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string detected_class\n"
"int16 cx\n"
"int16 cy\n"
;
  }

  static const char* value(const ::mission_node::Bounding_box_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mission_node::Bounding_box_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.detected_class);
      stream.next(m.cx);
      stream.next(m.cy);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Bounding_box_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mission_node::Bounding_box_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mission_node::Bounding_box_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "detected_class: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.detected_class);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "cx: ";
    Printer<int16_t>::stream(s, indent + "  ", v.cx);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "cy: ";
    Printer<int16_t>::stream(s, indent + "  ", v.cy);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MISSION_NODE_MESSAGE_BOUNDING_BOX_H
