// Generated by gencpp from file mission_node/class_pub.msg
// DO NOT EDIT!


#ifndef MISSION_NODE_MESSAGE_CLASS_PUB_H
#define MISSION_NODE_MESSAGE_CLASS_PUB_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mission_node
{
template <class ContainerAllocator>
struct class_pub_
{
  typedef class_pub_<ContainerAllocator> Type;

  class_pub_()
    : classify_class()
    , confidence(0)  {
    }
  class_pub_(const ContainerAllocator& _alloc)
    : classify_class(_alloc)
    , confidence(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _classify_class_type;
  _classify_class_type classify_class;

   typedef int16_t _confidence_type;
  _confidence_type confidence;





  typedef boost::shared_ptr< ::mission_node::class_pub_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mission_node::class_pub_<ContainerAllocator> const> ConstPtr;

}; // struct class_pub_

typedef ::mission_node::class_pub_<std::allocator<void> > class_pub;

typedef boost::shared_ptr< ::mission_node::class_pub > class_pubPtr;
typedef boost::shared_ptr< ::mission_node::class_pub const> class_pubConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mission_node::class_pub_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mission_node::class_pub_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mission_node::class_pub_<ContainerAllocator1> & lhs, const ::mission_node::class_pub_<ContainerAllocator2> & rhs)
{
  return lhs.classify_class == rhs.classify_class &&
    lhs.confidence == rhs.confidence;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mission_node::class_pub_<ContainerAllocator1> & lhs, const ::mission_node::class_pub_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mission_node

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mission_node::class_pub_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mission_node::class_pub_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mission_node::class_pub_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mission_node::class_pub_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mission_node::class_pub_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mission_node::class_pub_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mission_node::class_pub_<ContainerAllocator> >
{
  static const char* value()
  {
    return "236eed931e14e0bcfce3c6d0f10d08fb";
  }

  static const char* value(const ::mission_node::class_pub_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x236eed931e14e0bcULL;
  static const uint64_t static_value2 = 0xfce3c6d0f10d08fbULL;
};

template<class ContainerAllocator>
struct DataType< ::mission_node::class_pub_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mission_node/class_pub";
  }

  static const char* value(const ::mission_node::class_pub_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mission_node::class_pub_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string classify_class\n"
"int16 confidence\n"
;
  }

  static const char* value(const ::mission_node::class_pub_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mission_node::class_pub_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.classify_class);
      stream.next(m.confidence);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct class_pub_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mission_node::class_pub_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mission_node::class_pub_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "classify_class: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.classify_class);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "confidence: ";
    Printer<int16_t>::stream(s, indent + "  ", v.confidence);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MISSION_NODE_MESSAGE_CLASS_PUB_H
